### ISSUE TITLE
what is the mean of GCN network?

### ISSUE THREAD

**Issue by xiaopanchen** [shuxjweb/pixel_sampling#10]
(1) what is the mean of GCN network?
(2) How to produce mask_6 dataset? what is the role of maks_6?
THk.

**Comment by shuxjweb** [comment]
Hi, recent days are very busy and sorry for the late reply.
1. The GCN network is not used in this project and maybe used in other research. You can ignore it.
2. First, you can use a human parsing model [SCHP](https://github.com/GoGoDuck912/Self-Correction-Human-Parsing) to predict the mask. Then, the predicted results need to be processed and details can be seen at [https://github.com/shuxjweb/pixel_sampling/issues/2](url).

**Comment by xiaopanchen** [comment]
Thk
