### ISSUE TITLE
Details on recombining 18 parts into 6 parts

### ISSUE THREAD

**Issue by weihongwei3** [shuxjweb/pixel_sampling#2]
Thanks for the contribution of this paper in cloth-changing re-id. Now I have two questions:
(1)As for the description of recombining 18 parts into 6 parts, I want to know how to do it. For example, for the "Head" part, is it a combination of the "Hair" and "face" channels? Dose the "upper-clothes" part only extract a single channel? The same goes for other parts.
(2)Were the original 18 parts obtained through ATR's pre-training model?
I will continue to follow your work and look forward to your reply.

**Comment by shuxjweb** [comment]
(1) The class number of ATR dataset is 18, including  ['Background', 'Hat', 'Hair', 'Sunglasses', 'Upper-clothes', 'Skirt', 'Pants', 'Dress', 'Belt', 'Left-shoe', 'Right-shoe', 'Face', 'Left-leg', 'Right-leg', 'Left-arm', 'Right-arm', 'Bag', 'Scarf']. We recombine them into 6 classes:  {'Background': 0, 'Hat': 1, 'Hair': 1, 'Sunglasses': 1, 'Upper-clothes': 2, 'Skirt': 3, 'Pants': 3, 'Dress': 2, 'Belt': 3, 'Left-shoe': 5, 'Right-shoe': 5, 'Face': 1, 'Left-leg': 5, 'Right-leg': 5, 'Left-arm': 4, 'Right-arm': 4, 'Bag': 4, 'Scarf': 2}

(2) Yes. The ATR's pre-training model was used in our experiments. We have tested three models pre-trained on LIP, ATR, Pascal, respectively. The model pre-trained on ATR has better segmentation results. Of course, you can fuse three results. It would be better. You can try it.
