### ISSUE TITLE
How did you processed the PRCC dataset

### ISSUE THREAD

**Issue by Ehsan-Yaghoubi** [shuxjweb/pixel_sampling#4]
Hello.

In the PRCC dataset original paper, the authors have mentioned that they have randomly generated a one-shot gallery. But I cannot see that you follow the same rule. Am I right? 

Meanwhile, the RGB PRCC dataset has been introduced in three folders (`train`-`test`-`val`) within `train` and `val` folders, there are folders that include the images related to persons, and in `test` folder, there are three folders named `A`, `B`, and `C`. However, in your code, I see that you have different directories such as `./train`, `./test/query`, and `./test/gallery `(see `https://github.com/shuxjweb/pixel_sampling/blob/34015519edf9b682693024abf128345037f6ccf5/data/datasets/prcc.py#L66`)

Could you please clarify how have you folderized the PRCC dataset? I would like to run the `prcc.py` code.

My guess is that you have considered folder A as gallery and folders B and C as query. Right?

Thanks

**Comment by shuxjweb** [comment]
Please use the script "prcc_gcn.py". In all the running scripts, we do not use "prcc.py".  For example, parser.add_argument('--dataset', type=str, default='prcc_gcn'). This line defines which script you should use.
