### ISSUE TITLE
not exist:  .npy file

### ISSUE THREAD

**Issue by mumuner** [shuxjweb/pixel_sampling#5]
Hi，there is an error which show not exist .npy file. Can you tell me how to get the .npy file? since though schp I can get the .png file only. please?

**Comment by shuxjweb** [comment]
The .npy file is the predicted result of segmentation model.  Assume the shape of a RGB image is [3, 256, 128], the shape of predicted mask is [256, 128, 6]. '6' is the predicted probability of six parts. I save it using the function of np.save().

**Comment by mumuner** [comment]
Hi, since your artical said that the model predicted 18 parts,  I use SCHP with  pretrained model on atr dataset to get the .npy file. but I still confused about how to  recombined them to get six parts?   Can you give me more details?

**Comment by mumuner** [comment]
thank you for your kindness replay

**Comment by shuxjweb** [comment]
The predicted mask is quite large. You can download it from this link if you have interest.  
link: https://pan.baidu.com/s/1sX1qFgo3I-4OfEdEr-opSg      
password: r9kc

**Comment by shuxjweb** [comment]
The detail combination : https://github.com/shuxjweb/pixel_sampling/issues/2
