### ISSUE TITLE
The GLOBAL model is Part-based Convolutional Baseline.

### ISSUE THREAD

**Issue by mumuner** [shuxjweb/pixel_sampling#6]
Hi, I run your code and find that your global model is PCB, and cmc1: 62.2%, mAP: 55.9%. But in your paper you said the baseline is BoT, r1：67.7% mAP: 62.3%, I didn't find the BoT model in your code.

**Comment by shuxjweb** [comment]
The global model is not PCB, please see the model code. The model name is pcb_global, but it is BoT in fact.
