### ISSUE TITLE
mask on google drive: https://drive.google.com/drive/folders/1HaIoKRj1R4fxjVQ9Qg_IEk2_46b1hniH?usp=sharing

### ISSUE THREAD

**Issue by wangxiao5791509** [shuxjweb/pixel_sampling#7]
https://drive.google.com/drive/folders/1HaIoKRj1R4fxjVQ9Qg_IEk2_46b1hniH?usp=sharing

**Comment by Mr-corton** [comment]
Hello, may I ask how you process data using SCHP, with an output of 256 * 128? How to modify the official sample code？
