### ISSUE TITLE
The performance of PCB on PRCC dataset are different from other paper published.

### ISSUE THREAD

**Issue by mumuner** [shuxjweb/pixel_sampling#8]
Hi, I read a paper "You look so different! Haven’t I seen you a long time ago?", in the 4.3.2. prcc dataset chapter, the auther said you use a different evaluation setting, resulting to a high performance. Can you tell me what is the difference evaluation setting, and why your method is extremely high in prcc, have you try your method on other dataset? Please.

**Comment by shuxjweb** [comment]
Hi, thanks. When I did my work, the code of original PRCC dataset had not been released. I have communicated with one of the authors, so I implemented the code of loading data as I understood it. The test dataset is split into A, B, and C. In my code, the images in the folder B (same clothes) or C (different clothes)  are regarded as query, and the images in the foloder A are regarded as gallery.  I have noticed the paper you mentioned. Their data splits are the same with us. You can run their codes and please tell me if you understand the difference. I am very busy recently and will check it a few weeks later.
