### ISSUE TITLE
您好 请问能分享一下在self-correction-human-parsing中您训练好的trained model吗 

### ISSUE THREAD

**Issue by MarkYongWei** [shuxjweb/pixel_sampling#9]

**Comment by shuxjweb** [comment]
Hi, we haven't trained the human parsing model by ourselves. The pre-trained model is available at [SCHP](https://github.com/GoGoDuck912/Self-Correction-Human-Parsing). The predicted results need to be processed and details can be seen at [https://github.com/shuxjweb/pixel_sampling/issues/2](url).
